#!/usr/bin/env python
# src-git-pull
# Updates ~/src/ from GitHub repos
#
# Author: Daniel Gonzalez Gasull

try:
    import git
except:
    import subprocess
    HAS_GIT_LIB = False
else:
    HAS_GIT_LIB = True
import os


def pull_repo(directory):
    if HAS_GIT_LIB:
        repo = git.cmd.Git(subdir)
        print(repo.pull())
    else:
        os.chdir(subdir)
        subprocess.call(['git', 'pull'])
        os.chdir('..')


os.chdir(os.path.expanduser('~/src/'))
for directory in os.listdir('.'):
    if os.path.isdir(directory) and directory.endswith('gasull.github.com'):
        os.chdir(directory)
        for subdir in os.listdir('.'):
            if os.path.isdir(subdir):
                print('Updating %s/%s:' % (directory, subdir))
                pull_repo(subdir)
        os.chdir('..')
